### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ghost** [lehmenkuehler/camera-triggerbot#1]
first of all, nice release, been wanting to try something like this for awhile.
any tips on configuring the mouse for this? as in how to set up the cables and stuff to the relay etc. ill probably do something like this except use a webcam+ 2nd pc instead to save on costs. contact me on discord if possible, defense#8186

**Comment by lehmenkuehler** [comment]
Solder the cables to the switch, drill a hole into the mouse case, maybe setup a stress relief somehow (glue it or so), remove the original mouse cable coating and braid the new and the old cables into one strand.

Using a normal PC instead of a Pi will work if you have a GPIO interface. Using a generic webcam however will not work: I don't know what a common focal length for a webcam is but it usually looks like 6mm - 15mm full frame equivalent. The setup here uses a 50mm Canon lens which makes for a 625mm full frame equivalent (the Raspberry Pi High Quality Camera has a 12.5 crop factor when using video mode). In other words, you need a focal length above 35mm to make it look like a telephoto lens with a sensor that small. You need to get a close up of the monitor center to make all of this work properly. Depending on how close the camera will be you may also need a macro extension tube and a low aperture (like 1:1.8) so you don't have to amp up the ISO. A generic webcam can't handle all of that. I guess I'll have to make an update on the lens choices in the readme. I added you.
