### ISSUE TITLE
Guide to the wiring

### ISSUE THREAD

**Issue by jordn24** [lehmenkuehler/camera-triggerbot#3]
Hey, 

This project looks awesome and am keen to try it myself. I however pretty much only have software skills and little to no hardware skills. It would be helpful if you could  outline the general wiring for the project, e.g. Connecting the mouse, relay/mechanical key wiring, LEDs, what you soldered etc.

Just a simple outline would be great as I can learn on the fly and fill in the gaps myself. Just struggling to get a start and assuming i am just missing the basics.

Thanks!

My disc is jordn24#5777 if you'd rather just add me there.

**Comment by lehmenkuehler** [comment]
I'll complete the guide with some infos about that.
Here are some examples until then:
https://www.electronicshub.org/control-a-relay-using-raspberry-pi/ (instead of the light bulb connect to the pins of the clicking module inside the mouse)
https://raspberrypihq.com/use-a-push-button-with-raspberry-pi-gpio/ (same thing as a mechanical keyboard switch)
https://thepihut.com/blogs/raspberry-pi-tutorials/27968772-turning-on-an-led-with-your-raspberry-pis-gpio-pins (LEDs are optional, maybe do that last)
I added you in case you have specific questions, it might take a while until I have a proper guide.
