### ISSUE TITLE
Little question. 

### ISSUE THREAD

**Issue by ghost** [lehmenkuehler/camera-triggerbot#4]
Hey @lehmenkuehler, 

First of all, let me say that I really appreciate this project. I am currently working on a similar project myself. However, I have a question that is not really related to the project. Could you tell me what camera was used to take the photos visible on the repository? I find them very beautiful and of professional quality.

Thanks in advance, 

I'm looking forward to seeing more cool projects like this one ! 

Charly,

**Comment by lehmenkuehler** [comment]
Hey Charly,

in fact, your question is a little related to the project itself because whether you're trying to get high quality image output from the Raspberry Pi camera or high quality photos from an aesthetics standpoint, the same rules apply. What's much more important than the camera is the lens used (and the light), so I'll tell you both:

The overview picture of the desk: Canon M50 with a Sigma 24mm 1.4 and a Viltrox EF-EOS speed booster.
The detailed pictures of the mouse, key, lenses, etc.: Canon M50 with a Canon EF 50mm 1.8 STM and a Canon EF-EOS adapter.

There's a little lens-ception here because I tested those lenses that I used to document the whole thing for the cheat itself on the RP camera. :-)

Leander

**Comment by ghost** [comment]
Hi Leander, 

Thank you for the time you took to answer me and the details you provided, I really appreciate it. 

I look forward to witnessing the birth of more projects on this account that exhibit the same level of high-quality content !

You rock ! 


Charly,
